#!/usr/bin/env python3
"""
Observability Solution Accelerator — One-Command Experience

Usage:
    python accelerator.py --subscription-id <SUB_ID> --customer-name <NAME> --resource-group <RG>

This script orchestrates the full accelerator pipeline:
  1. Scans the Azure subscription to discover all resources
  2. Generates Azure Workbook JSON files based on discovered resources
  3. Generates a Terraform .tfvars file with auto-detected feature flags
  4. Optionally runs terraform init + plan + apply

Prerequisites:
  - Azure CLI authenticated (az login)
  - Python packages: pip install -r discovery/requirements.txt
  - Terraform >= 1.5.0 (for deploy step)
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parent
DISCOVERY_DIR = ROOT_DIR / "discovery"
INFRA_DIR = ROOT_DIR / "infra"
GENERATED_DIR = ROOT_DIR / "generated-workbooks"


def run_cmd(cmd, description, dry_run=False):
    """Run a shell command and stream output."""
    print(f"\n{'[DRY RUN] ' if dry_run else ''}>>> {description}")
    print(f"    $ {' '.join(cmd)}")
    if dry_run:
        return 0
    result = subprocess.run(cmd, cwd=str(ROOT_DIR))
    return result.returncode


def step_discover(args):
    """Step 1: Scan the Azure subscription."""
    print("\n" + "=" * 70)
    print("  STEP 1: Discovering resources in subscription")
    print("=" * 70)

    discovery_output = str(DISCOVERY_DIR / "discovered-resources.json")
    cmd = [
        sys.executable,
        str(DISCOVERY_DIR / "scan_subscription.py"),
        "--subscription-id", args.subscription_id,
        "--output", discovery_output,
    ]
    rc = run_cmd(cmd, "Scanning subscription for resources...", args.dry_run)
    if rc != 0 and not args.dry_run:
        print("ERROR: Discovery scan failed. Check Azure CLI authentication.")
        return None
    return discovery_output


def step_generate_workbooks(args, discovery_file, workspace_id):
    """Step 2: Generate workbooks from discovery output."""
    print("\n" + "=" * 70)
    print("  STEP 2: Generating workbooks based on discovered resources")
    print("=" * 70)

    output_dir = str(GENERATED_DIR)
    cmd = [
        sys.executable,
        str(DISCOVERY_DIR / "generate_workbooks.py"),
        "--discovery-file", discovery_file,
        "--workspace-id", workspace_id,
        "--subscription-id", args.subscription_id,
        "--output-dir", output_dir,
        "--customer-name", args.customer_name,
    ]
    rc = run_cmd(cmd, "Generating workbook templates...", args.dry_run)
    if rc != 0 and not args.dry_run:
        print("ERROR: Workbook generation failed.")
        return None
    return output_dir


def step_generate_tfvars(args, discovery_file, workbook_dir):
    """Step 3: Generate a .tfvars file from discovery output."""
    print("\n" + "=" * 70)
    print("  STEP 3: Generating Terraform .tfvars from discovery")
    print("=" * 70)

    tfvars_path = INFRA_DIR / f"{args.customer_name}.auto.tfvars"

    if args.dry_run:
        print(f"    [DRY RUN] Would generate {tfvars_path}")
        return str(tfvars_path)

    # Read discovery output
    with open(discovery_file) as f:
        discovery = json.load(f)

    flags = discovery.get("feature_flags", {})

    # Build workbook_files map from generated workbooks
    workbook_files = {}
    manifest_path = Path(workbook_dir) / "deploy-manifest.json"
    if manifest_path.exists():
        with open(manifest_path) as f:
            manifest = json.load(f)
        for wb in manifest.get("workbooks", []):
            rel_path = os.path.relpath(
                Path(workbook_dir) / wb["file"], INFRA_DIR
            ).replace("\\", "/")
            workbook_files[wb["display_name"]] = rel_path

    # Build .tfvars content
    lines = [
        f'# Auto-generated by accelerator.py on {datetime.now(timezone.utc).isoformat()}',
        f'# Discovery source: {discovery_file}',
        f'',
        f'subscription_id    = "{args.subscription_id}"',
        f'customer_name      = "{args.customer_name}"',
        f'resource_group_name = "{args.resource_group}"',
        f'location           = "{args.location}"',
        f'',
        f'# --- Auto-detected feature flags ---',
        f'enable_sentinel             = true',
        f'enable_network_observability = {str(flags.get("enable_network_observability", True)).lower()}',
        f'enable_iot_hub              = {str(flags.get("enable_iot_hub", False)).lower()}',
        f'enable_aks                  = {str(flags.get("enable_aks", False)).lower()}',
        f'enable_amba                 = {str(flags.get("enable_amba", False)).lower()}',
        f'enable_workbooks            = {str(len(workbook_files) > 0).lower()}',
        f'',
    ]

    # Add amba_services if AMBA is enabled
    amba_services = flags.get("amba_services", [])
    if amba_services:
        services_str = ", ".join(f'"{s}"' for s in amba_services)
        lines.append(f'amba_services = [{services_str}]')
        lines.append('')

    # Add workbook_files map
    if workbook_files:
        lines.append('workbook_files = {')
        for name, path in workbook_files.items():
            lines.append(f'  "{name}" = "{path}"')
        lines.append('}')
        lines.append('')

    # Write .tfvars
    tfvars_content = "\n".join(lines) + "\n"
    with open(tfvars_path, "w") as f:
        f.write(tfvars_content)

    print(f"    Generated: {tfvars_path}")
    print(f"    Feature flags: {json.dumps(flags, indent=2)}")
    print(f"    Workbooks: {len(workbook_files)} files mapped")

    return str(tfvars_path)


def step_terraform(args, tfvars_path):
    """Step 4: Run Terraform init + plan + apply."""
    print("\n" + "=" * 70)
    print("  STEP 4: Deploying with Terraform")
    print("=" * 70)

    tfvars_file = os.path.basename(tfvars_path)

    # terraform init
    rc = run_cmd(
        ["terraform", "init"],
        "Initializing Terraform...",
        args.dry_run,
    )
    if rc != 0 and not args.dry_run:
        print("ERROR: terraform init failed.")
        return False

    # terraform plan
    rc = run_cmd(
        ["terraform", "plan", f"-var-file={tfvars_file}", "-out=accelerator.tfplan"],
        "Planning deployment...",
        args.dry_run,
    )
    if rc != 0 and not args.dry_run:
        print("ERROR: terraform plan failed.")
        return False

    if not args.auto_approve:
        print("\n    Review the plan above. Run with --auto-approve to apply automatically.")
        print(f"    Or manually: cd infra && terraform apply accelerator.tfplan")
        return True

    # terraform apply
    rc = run_cmd(
        ["terraform", "apply", "accelerator.tfplan"],
        "Applying infrastructure...",
        args.dry_run,
    )
    if rc != 0 and not args.dry_run:
        print("ERROR: terraform apply failed.")
        return False

    return True


def main():
    parser = argparse.ArgumentParser(
        description="Observability Solution Accelerator — One-Command Deployment",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Full pipeline (discover → generate → plan only)
  python accelerator.py --subscription-id abc-123 --customer-name contoso --resource-group rg-contoso-obs

  # Full pipeline with auto-deploy
  python accelerator.py --subscription-id abc-123 --customer-name contoso --resource-group rg-contoso-obs --auto-approve

  # Dry run (preview all commands without executing)
  python accelerator.py --subscription-id abc-123 --customer-name contoso --resource-group rg-contoso-obs --dry-run

  # Skip discovery (use existing discovery file)
  python accelerator.py --subscription-id abc-123 --customer-name contoso --resource-group rg-contoso-obs --skip-discovery
        """,
    )

    parser.add_argument("--subscription-id", required=True, help="Azure subscription ID")
    parser.add_argument("--customer-name", required=True, help="Customer name (lowercase, no spaces)")
    parser.add_argument("--resource-group", required=True, help="Azure resource group name")
    parser.add_argument("--location", default="westus2", help="Azure region (default: westus2)")
    parser.add_argument("--auto-approve", action="store_true", help="Auto-approve terraform apply")
    parser.add_argument("--dry-run", action="store_true", help="Preview commands without executing")
    parser.add_argument("--skip-discovery", action="store_true", help="Skip discovery, use existing discovered-resources.json")
    parser.add_argument("--skip-terraform", action="store_true", help="Only run discovery + workbook generation")

    args = parser.parse_args()

    print("=" * 70)
    print("  OBSERVABILITY SOLUTION ACCELERATOR")
    print("=" * 70)
    print(f"  Subscription:    {args.subscription_id}")
    print(f"  Customer:        {args.customer_name}")
    print(f"  Resource Group:  {args.resource_group}")
    print(f"  Region:          {args.location}")
    print(f"  Mode:            {'DRY RUN' if args.dry_run else 'LIVE'}")
    print("=" * 70)

    # Step 1: Discovery
    if args.skip_discovery:
        discovery_file = str(DISCOVERY_DIR / "discovered-resources.json")
        if not Path(discovery_file).exists() and not args.dry_run:
            print(f"ERROR: --skip-discovery specified but {discovery_file} not found.")
            print("       Run discovery first, or remove --skip-discovery.")
            sys.exit(1)
        print(f"\n  Skipping discovery, using: {discovery_file}")
    else:
        discovery_file = step_discover(args)
        if discovery_file is None:
            sys.exit(1)

    # Determine workspace ID (will be created by Terraform, use placeholder for generation)
    workspace_id = f"/subscriptions/{args.subscription_id}/resourceGroups/{args.resource_group}/providers/Microsoft.OperationalInsights/workspaces/la-{args.customer_name}-obs"

    # Step 2: Generate workbooks
    workbook_dir = step_generate_workbooks(args, discovery_file, workspace_id)
    if workbook_dir is None:
        sys.exit(1)

    # Step 3: Generate .tfvars
    tfvars_path = step_generate_tfvars(args, discovery_file, workbook_dir)
    if tfvars_path is None:
        sys.exit(1)

    # Step 4: Terraform
    if args.skip_terraform:
        print("\n  Skipping Terraform (--skip-terraform). Files generated:")
        print(f"    Discovery:  {discovery_file}")
        print(f"    Workbooks:  {workbook_dir}/")
        print(f"    Terraform:  {tfvars_path}")
        print(f"\n  Next steps:")
        print(f"    cd infra")
        print(f"    terraform init")
        print(f"    terraform plan -var-file={os.path.basename(tfvars_path)}")
        print(f"    terraform apply -var-file={os.path.basename(tfvars_path)}")
    else:
        success = step_terraform(args, tfvars_path)
        if not success:
            sys.exit(1)

    print("\n" + "=" * 70)
    print("  ACCELERATOR COMPLETE")
    print("=" * 70)
    print(f"  Discovery output:   {discovery_file}")
    print(f"  Generated workbooks: {workbook_dir}/")
    print(f"  Terraform config:   {tfvars_path}")
    print("=" * 70)


if __name__ == "__main__":
    main()
